stages:
  - test

.elixir:
  image: gitlab.otters.xyz:5005/product/guild/elixir/dockerfiles/docker-ci-elixir/docker-ci-elixir:1.15
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV


.test:elixir:
  extends: .elixir_cache_pull
  stage: test
  variables:
    MIX_ENV: test
  script:
    - mix test

