include:
  - project: product/business/experience/ci-config
    file: presets/elixir.yml

.elixir:
  image: gitlab.otters.xyz:5005/product/guild/elixir/dockerfiles/docker-ci-elixir/docker-ci-elixir:1.15

variables:
  TEST_ELIXIR_DIALYZER: "false"
  PROJECT_NAME: corporate-integrations-api
  PROJECT_NAMESPACE: corporate
  OMIT_SANDBOX: 'true'

.test:elixir:
  extends: .elixir_cache_pull
  stage: test
  needs: ["build:elixir"]
  variables:
    # MYSQL_HOSTNAME: gitlab-mysql
    # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # MYSQL_ROOT_HOST: "%"

  services:
    # - name: mysql:8
    #   alias: gitlab-mysql

  script:
    # - tries=50;
    #   while [ $tries -gt 0 ]; do
    #     set +e;
    #     nc -zvw10 gitlab-mysql 3306 && break;
    #     set -e;
    #     tries=$(($tries - 1));
    #     sleep 10;
    #   done;
    # - mix ecto.setup
    - mix test
