@startuml Architecture

package bank {
  class Service

  package models {
    class Account
    class AccountId
    class Money
    class Currency
  }

  package infrastructure {
    class InMemoryAccountRepository
  }
}

package test {
  package test.bank {
    class ServiceTest

    package test.bank.models {
      class AccountTest
  }
}

ServiceTest --> Service
AccountTest --> Account


Service --> InMemoryAccountRepository
InMemoryAccountRepository --> Account
Service --> Account
Account *--> AccountId
Account *--> Money
Money *--> Currency


@enduml